[project]
name = "celery-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery[redis]>=5.6.0",
    "flask>=3.1.2",
    "gevent>=25.9.1",
    "gunicorn>=23.0.0",
    "redis>=6.4.0",
]
